services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
      - 'MONGO_INITDB_ROOT_PASSWORD=admin'
    ports:
      - '27017:27017'
    volumes:
      - mongo-notes-volume:/data/db
    networks:
      - mongo-notes-network
  mongo-express:
    image: 'mongo-express:latest'
    ports:
      - '8081:8081'
    networks:
      - mongo-notes-network
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/?authSource=admin
volumes:
  mongo-notes-volume:

networks:
  mongo-notes-network:
    driver: bridge