spring:
  application:
    name: vue-spring-boot-mongo-template

  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:vue-spring-boot-mongo-template}
      username: ${MONGO_USER:admin}
      password: ${MONGO_PWD:admin}
      authentication-database: ${MONGO_AUTH_DB:admin}
      auto-index-creation: ${MONGO_AUTO_INDEX:true}

  docker:
    compose:
      enabled: false

logging:
  level:
    org:
      mongodb:
        driver: DEBUG
      springframework:
        data:
          mongodb:
            MongoTransactionManager: DEBUG
            core:
              MongoTemplate: TRACE
            convert:
              DefaultDbRefResolver: TRACE

springdoc:
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    filter: true
    tags-sorter: alpha

vue-spring-boot-mongo-template:
  jwt:
    token:
      secret: ${MONGO_NOTES_JWT_SECRET}
      validity-period: ${MONGO_NOTES_JWT_VALIDITY_PERIOD:300}