spring:
  application:
    name: mongo-notes

  data:
    mongodb:
      host: ${MONGO_HOST:localhost}
      port: ${MONGO_PORT:27017}
      database: ${MONGO_DB:mongo-notes}
      username: ${MONGO_USER:admin}
      password: ${MONGO_PWD:admin}
      authentication-database: ${MONGO_AUTH_DB:admin}
      auto-index-creation: ${MONGO_AUTO_INDEX:true}

  docker:
    compose:
      enabled: false

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG

springdoc:
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    filter: true
    tags-sorter: alpha

mongo-notes:
  jwt:
    token:
      secret: ${MONGO_NOTES_JWT_SECRET}
      validity-period: ${MONGO_NOTES_JWT_VALIDITY_PERIOD:300}